/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed2;
  GtkWidget *button5;
  GtkWidget *button7;
  GtkWidget *button6;
  GtkWidget *button8;
  GtkWidget *entry1;
  GtkWidget *label1;
  GtkWidget *entry2;
  GtkWidget *label6;
  GtkWidget *label5;
  GtkWidget *comboboxentry1;
  GtkWidget *calendar1;
  GtkWidget *label2;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *radiobutton3;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkWidget *label3;
  GtkWidget *label7;
  GtkWidget *comboboxentry2;
  GtkWidget *button9;
  GtkWidget *label9;
  GtkWidget *label8;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window2), fixed2);

  button5 = gtk_button_new_with_mnemonic (_("User Management"));
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed2), button5, 0, 0);
  gtk_widget_set_size_request (button5, 144, 32);

  button7 = gtk_button_new_with_mnemonic (_("Polling station management"));
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed2), button7, 312, 0);
  gtk_widget_set_size_request (button7, 208, 32);

  button6 = gtk_button_new_with_mnemonic (_("Election Management"));
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed2), button6, 144, 0);
  gtk_widget_set_size_request (button6, 168, 32);

  button8 = gtk_button_new_with_mnemonic (_("Electora list management"));
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed2), button8, 520, 0);
  gtk_widget_set_size_request (button8, 184, 32);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1, 168, 56);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (entry1), _("add your ID"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  label1 = gtk_label_new (_("Identifier:"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed2), label1, 8, 64);
  gtk_widget_set_size_request (label1, 96, 16);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2, 168, 320);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  label6 = gtk_label_new (_("municipality:"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 0, 120);
  gtk_widget_set_size_request (label6, 136, 16);

  label5 = gtk_label_new (_("date:"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed2), label5, 0, 168);
  gtk_widget_set_size_request (label5, 96, 16);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxentry1, 160, 112);
  gtk_widget_set_size_request (comboboxentry1, 189, 29);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed2), calendar1, 168, 160);
  gtk_widget_set_size_request (calendar1, 106, 72);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  label2 = gtk_label_new (_("Orientation:"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed2), label2, 16, 272);
  gtk_widget_set_size_request (label2, 112, 16);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("left"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton1, 136, 272);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("center"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton2, 240, 272);
  gtk_widget_set_size_request (radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("right"));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton3, 376, 272);
  gtk_widget_set_size_request (radiobutton3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  spinbutton2_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton2, 328, 200);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  spinbutton3_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton3, 416, 200);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  spinbutton4_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton4, 504, 200);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  label3 = gtk_label_new (_("Id head of the list:"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed2), label3, 0, 328);
  gtk_widget_set_size_request (label3, 160, 16);

  label7 = gtk_label_new (_("polling station:"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 16, 384);
  gtk_widget_set_size_request (label7, 120, 16);

  comboboxentry2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry2);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxentry2, 152, 376);
  gtk_widget_set_size_request (comboboxentry2, 189, 29);

  button9 = gtk_button_new_with_mnemonic (_("submit"));
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed2), button9, 392, 472);
  gtk_widget_set_size_request (button9, 66, 29);

  label9 = gtk_label_new (_("error"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 544, 480);
  gtk_widget_set_size_request (label9, 41, 17);

  label8 = gtk_label_new (_("add the candidates:"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 0, 448);
  gtk_widget_set_size_request (label8, 176, 16);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2, button5, "button5");
  GLADE_HOOKUP_OBJECT (window2, button7, "button7");
  GLADE_HOOKUP_OBJECT (window2, button6, "button6");
  GLADE_HOOKUP_OBJECT (window2, button8, "button8");
  GLADE_HOOKUP_OBJECT (window2, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window2, label1, "label1");
  GLADE_HOOKUP_OBJECT (window2, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window2, label6, "label6");
  GLADE_HOOKUP_OBJECT (window2, label5, "label5");
  GLADE_HOOKUP_OBJECT (window2, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (window2, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (window2, label2, "label2");
  GLADE_HOOKUP_OBJECT (window2, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (window2, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (window2, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (window2, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (window2, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (window2, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (window2, label3, "label3");
  GLADE_HOOKUP_OBJECT (window2, label7, "label7");
  GLADE_HOOKUP_OBJECT (window2, comboboxentry2, "comboboxentry2");
  GLADE_HOOKUP_OBJECT (window2, button9, "button9");
  GLADE_HOOKUP_OBJECT (window2, label9, "label9");
  GLADE_HOOKUP_OBJECT (window2, label8, "label8");

  return window2;
}

